### ISSUE TITLE
PN inspiral quantities

### ISSUE THREAD

**Issue by nilsvu** [moble/PostNewtonian.jl#41]
Hi Mike! I'm considering to use your new PN implementation to get good initial orbital parameters for eccentricity reduction in SpECTRE. Currently I use the SpEC scripts for this. Specifically, see [here](https://github.com/sxs-collaboration/spectre/blob/develop/support/Pipelines/EccentricityControl/InitialOrbitalParameters.py) for the function in SpECTRE that calls the SpEC scripts and returns initial orbital parameters. My question is: does the Julia code already expose equivalents to the `omegaAndAdot` and `nOrbitsAndTotalTime` functions in SpEC's `ZeroEccParamsFromPN.py` script, or would those be easy to add?

**Comment by nilsvu** [comment]
Edit: I got the number of orbits and time to merger from `sxs.julia.PNWaveform`. So the only remaining question is if the PN approximation for `Omega(r, q, chi1, chi2)` and `adot(r, q, chi1, chi2)` is available as well somehow? Here, `r` is the coordinate separation in a quasicircular binary.

**Comment by moble** [comment]
The output from `sxs.julia.PNWaveform` also has a field containing the PN expansion parameter `v` as a function of time, which is defined as $v := (M \Omega)^{1/3}$, so I think `Omega = w.v**3 / (w.M1 + w.M2)` would be what you want.

As for `adot`, I don't know that I've actually ever seen a PN approximation directly for that.  It's certainly not involved in the standard (quasicircular) PN computation.  I'm on vacation at the moment, so I'm afraid I won't be able to help much for the next couple weeks.

**Comment by nilsvu** [comment]
Ok thank you! Have a good vacation! We can talk more when you're back. For then:

`PNWaveform` takes `Omega_i` as input and integrates the `orbital_evolution`. That's great and we can use it for the number of orbits and the time to merger. But I'm also looking for just the approximation of `Omega(r, q, chi1, chi2)` and `adot(r, q, chi1, chi2` without having to do the orbit integration. That's at least how SpEC determines these initial orbital parameters.

**Comment by nilsvu** [comment]
Thanks @moble! I'll give this a try and see if we can get better zero-ecc estimates from it :)

**Comment by nilsvu** [comment]
Works very well as far as I can tell! Thanks for providing this :)
