### ISSUE TITLE
All approximants are doing the same thing

### ISSUE THREAD

**Issue by vijayvarma392** [moble/PostNewtonian.jl#56]
Here is a script to reproduce the issue
```
import numpy as np
import matplotlib.pyplot as plt

# Start the Julia session
from sxs.julia import PNWaveform

q = 1.0
chiA0 = [0, 0, 0.5]
chiB0 = [0, 0, 0.5]
omega_ref = 1e-2

w_T1 = PNWaveform(q/(1+q), 1/(1+q), np.array(chiA0), np.array(chiB0),
                    omega_ref, approximant='TaylorT1')
plt.plot(w_T1.t, w_T1.data.T[4], label='TaylorT1')

w_T4 = PNWaveform(q/(1+q), 1/(1+q), np.array(chiA0), np.array(chiB0),
                    omega_ref, approximant='TaylorT4')
plt.plot(w_T4.t, w_T4.data.T[4], label='TaylorT4', ls='--')

w_T5 = PNWaveform(q/(1+q), 1/(1+q), np.array(chiA0), np.array(chiB0),
                    omega_ref, approximant='TaylorT5')
plt.plot(w_T5.t, w_T5.data.T[4], label='TaylorT5', ls='-.')

plt.ylim(-0.2, 0.2)
plt.legend()
plt.savefig('test.png')
plt.close()

# Plot differences
plt.plot(w_T1.t, np.abs(w_T1.data.T[4] - w_T4.data.T[4]), label='T1-T4')
plt.plot(w_T1.t, np.abs(w_T1.data.T[4] - w_T5.data.T[4]), label='T1-T5')
plt.legend()
plt.title('Differences')
plt.savefig('test_diff.png')
```

And the plots generated:

<img width="649" alt="image" src="https://github.com/user-attachments/assets/fb25ceb6-6f45-4425-bb0d-eca9e67cec5b">

<img width="649" alt="image" src="https://github.com/user-attachments/assets/11c4ba79-6b04-43d1-871d-f19b718a5259">

**Comment by moble** [comment]
Ah, sorry.  I was just rewriting the part of the code that switches approximants and forgot about a stray kwarg I left in there.  The Julia package is out; the pypi and conda versions are making their way through the pipeline.

Closed by 50c2e5d.

**Comment by vijayvarma392** [comment]
That fixed it, thanks!
One curious thing is that, if I run the same script above, TaylorT4 is evolved 3x further than the other approximants, even after PN is clearly breaking down. Just making sure you are aware, as it might mean TaylorT4 is doing some unnecessary work:
<img width="663" alt="image" src="https://github.com/user-attachments/assets/acf281c2-e0e3-419b-8727-2dd76e344de5">

**Comment by moble** [comment]
That's right — one of the reasons I don't really bother with TaylorT4 is that it frequently has this problem because the $\dot{v}$ RHS is just a polynomial, which usually has a root in an inconvenient spot.  I tried using a more aggressive termination criterion to avoid this back in the GWFrames days, but people complained.  I just always use TaylorT1.
